### ISSUE TITLE
Co-op with OroPlatform's DataGridBundle?

### ISSUE THREAD

**Issue by ConneXNL** [sonata-project/SonataDatagridBundle#10]
It might be interesting to check https://github.com/orocrm/platform/tree/master/src/Oro/Bundle/DataGridBundle and see if any co-operation can be done.

It's never good to re-invent the wheel, especially with something that mind become a key in Symfony admin panels.

**Comment by rande** [comment]
@ConneXNL actually if you look at the OroPlateform history, they took the code from the Admin Bundle and adapt the code to their need.
