### ISSUE TITLE
Distinct on primary auto increment key

### ISSUE THREAD

**Issue by TimoFrenzel** [sonata-project/SonataDatagridBundle#44]
Sonata\DatagridBundle\Datagrid\Pager

We have several million records in the table.
It noticed that the ListView needs more than 3 minutes to open the page.

This file is the problem.
It is made a count (distinct id).
However, the id is always an autoincrement primary key.
This slows the whole considerably.

And here too: Sonata\DatagridBundle\Datagrid\ProxyQuery

**Comment by greg0ire** [comment]
Can you have a look at the history to find the commit where this keyword was added?

**Comment by TimoFrenzel** [comment]
> Can you have a look at the history to find the commit where this keyword was added?

What exactly do you mean? My English is not very good.

**Comment by greg0ire** [comment]
I mean use `git log -S DISTINCT` to find the commit that introduced it. Maybe there is a commit message that explains if and why this is needed ?

**Comment by TimoFrenzel** [comment]
> Fix pager query when using leftJoin  

hm,


The Query is:

```
SELECT 
  count(DISTINCT m0_.id) AS sclr0 
FROM 
  xxx m0_ 
  LEFT JOIN sss m1_ ON m0_s_id = m1_.id 
  LEFT JOIN aaa m2_ ON m1_.a_id = m2_.id 
  LEFT JOIN ooo m3_ ON m0_.o_id = m3_.id 
WHERE 
  m0_.position <> ?
```


Thats the same result when the query is:

```
SELECT 
  count(m0_.id) AS sclr0 
FROM 
  xxx m0_ 
  LEFT JOIN sss m1_ ON m0_s_id = m1_.id 
  LEFT JOIN aaa m2_ ON m1_.a_id = m2_.id 
  LEFT JOIN ooo m3_ ON m0_.o_id = m3_.id 
WHERE 
  m0_.position <> ?
```


Or not?

**Comment by greg0ire** [comment]
Can you link to the commit? Just type its sha1 hash, and a link will appear.

**Comment by TimoFrenzel** [comment]
114a51485512bbcbbd2a478d1d3a840a5f6c49a6
and
58c92ec18acbdf9a23e2ba156961e2fd219f4a42

**Comment by greg0ire** [comment]
Here is the explanation : https://github.com/sonata-project/SonataDatagridBundle/issues/4

**Comment by OskarStark** [comment]
Can we close this issue @TimoFrenzel ?
