### ISSUE TITLE
Add a tag with version to not confuse composer

### ISSUE THREAD

**Issue by sivolobov** [sonata-project/SonataDatagridBundle#8]
There is at least one bundle that depends on SonataDatagridBundle. And it is SonataUserBundle. But it depends on concrete version of SonataDatagridBundle (2.2) but now in this repository there are no tags at all. Someone with write access to the repository should do the small thing: add a tag (`git tag -a 2.2.0` or similar). It's not so hard.

**Comment by hason** [comment]
:+1:

**Comment by ste93cry** [comment]
:+1:, this bundle doesn't seem to be actively developed but please release a stable version to simplify `Composer` installation of `SonataUserBundle`

**Comment by Ma27** [comment]
:+1: the SonataNotificationBundle uses also this bundle.
I'd like to use only stable dependencies, but this bundle doesn't have any release.

ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
ping @rande for this, I don't know if this bundle is stable enough.

**Comment by core23** [comment]
@rande Can we get a release for this bundle?
